library(quantmod)
library(Quandl)
tmp=Quandl("OFDP/INDEX_BDI",trim_start="2009-01-01",sort=c("asc"))
BDI <- xts(tmp$Index,order.by=as.Date(tmp$Date))
rm(tmp)
colnames(BDI) <- c("Close")
getSymbols("^KS11;^VIX",from='2009-01-01')
mm <- specifyModel(Next(OpCl(KS11)) ~ OpCl(KS11) + Cl(VIX) + Cl(BDI))
tail(modelData(mm))
